### ISSUE TITLE
Employment Verification

### ISSUE THREAD

**Issue by ChoiSojung** [ChoiSojung/playover#14]
This will probably be a work-around - not true employment verification but using part of the email address to verify the user.

**Comment by mattyplo** [comment]
Currently the app handles sending a confirmation email to the user.  It may be better to have a cloud function or firebase handle that confirmation email.

**Comment by mattyplo** [comment]
Han, will research how to handle verification.

**Comment by mattyplo** [comment]
Parse the email to see if it matches with employer designation.  Check to see if user is registered with an email ending in  @AlaskaAir.com
